Fix broken tests
opennextjs/opennextjs-aws pull request #551
Opened 2024-10-14 14:18 UTC by socsieng

Initial PR to try and fix broken tests.

For: https://github.com/opennextjs/opennextjs-aws/issues/539

2024-10-14 19:09 UTC, conico974 reviewed
As for the test failing it's probably some kind of config in vitest itself.
Does it work locally ?

2024-10-14 19:09 UTC, conico974 commented on packages/tests-unit/tests/adapter.utils.test.ts
I'd rather have one test file per file. It makes it easier to know what's covered and what's not.
So it would be split in 2 `core/routing/util.test.ts` and `http/util.test.ts`

2024-10-14 21:11 UTC, socsieng commented
> As for the test failing it's probably some kind of config in vitest itself. Does it work locally ?

It was working locally. It is failing now after `git clean`. Looking into it.

2024-10-14 21:31 UTC, socsieng commented
Tests fixed. Let me know if you're happy to proceed. I can continue to flesh out additional tests in this PR or separate pull requests if you prefer.

2024-10-15 07:42 UTC, conico974 requested changes
Separate PR will be easier to review.
If you could just move the `cache.test.ts` following the same logic as the other files.
And delete `example.test.ts`

2024-10-15 08:44 UTC, conico974 approved these changes
LGTM
Thanks !!!

2024-10-15 08:44 UTC, merged